INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'1a', N'DPEM'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'1a', N'I009'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'1a', N'I010'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'1a', N'INGR'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'1a', N'PRIN'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'1a', N'TICK'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'1b', N'INOE'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2a', N'PRJU'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2a', N'SIJP'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2b', N'DIFP'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2b', N'OBSO'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2b', N'PROS'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2c', N'VIDA'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2d', N'SEPE'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2f', N'ALQU'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2f', N'CSIN'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2f', N'DECR'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2f', N'HIPO'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2f', N'HONO'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'2f', N'SDOM'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'4', N'DONA'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'6a', N'A006'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'6a', N'A007'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'9a', N'C394'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'9a', N'IMPU'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'9b', N'DCTR'); GO
INSERT INTO [confdgi]([confitem], [confconcep]) VALUES (N'9b', N'TICK'); GO
