INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'INGR', 'Ingresos en la empresa', 2, 'I', 'F501', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'PRIN', 'Ingresos Prorrateados ', 3, 'I', 'F503', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'I009', 'ART 3 - RG 3976 SAC ', 4, 'I', 'F504', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'A006', 'Deduccion especial adicional', 6, 'D', '', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'DPEM', 'Diferencia de plan empresa', 6, 'I', 'F506', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'A007', 'Deducción Especial Dto. 1242', 7, 'A', '', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'INOE', 'Ingresos en Otras Empresas', 10, 'I', 'F510', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'SIJP', 'Ded. Jubilacion y Ley 19.032', 21, 'L', 'F521', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'PRJU', 'Ded. Jubilacion y Ley Prorr.', 22, 'L', 'F522', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'OBSO', 'Ded. Obra Social', 25, 'L', 'F525', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'PROS', 'Ded. Obra SocialProrr.', 26, 'L', 'F526', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'VIDA', 'Ded. Seguro de Vida ', 33, 'D', 'F533', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'SEPE', 'Ded. Gastos de Sepelio', 34, 'D', 'F534', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'HIPO', 'Ded. Inter. Créd. Hipotecarios', 35, 'D', 'F535', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'SDOM', 'Ded. Sevicios Domésticos', 36, 'D', 'F536', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'CSIN', 'Ded. Aportes sindicales ', 37, 'D', 'F539', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'GNET', 'Determinación de EX KGANET', 50, 'D', 'F550', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'DIFP', 'Ded. Diferencia de Plan ', 51, 'D', 'F551', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'DONA', 'Ded. Donaciones ', 53, 'D', 'F553', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'HONO', 'Ded. Honorarios Médicos ', 54, 'D', 'F554', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'IMPU', 'Impuesto Retenido ', 999, 'N', '', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'ICHE', 'Impuesto al Deb/Cred', 1000, 'R', 'F537', 'O');
INSERT INTO RIGAESQ(Jdd, Concepto, Descrip, Orden, Signo, Formula, Tipo) VALUES (0, 'DCTR', 'Ded. Por Compras Tarj. Extr ', 1001, 'R', 'F540', 'O');
