INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('ADMINISTRA', 'REMPLES ', 'Parametros de REMPLES ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('ADMINISTRA', 'USUBCONJUNTO', 'Parametros de USUBCONJUNTO', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('CONSULTA', 'CONFISER', 'Parametros de CONFISER', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('CONSULTA', 'REMPLES ', 'Parametros de REMPLES ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('CONSULTAO ', 'RCTACOR ', 'Parametros de RCTACOR ', ' 0 0 0', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('CONSULTAO ', 'REMPLES ', 'Parametros de REMPLES ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'CONFIMAILSEG', 'Parametros de CONFIMAILSEG', 'R8cwF6xunXOcXGs6HBVXzylgl0Qbg4/QKnT4Z43ntJ2cREPiiFF8/gLh1rkP37sZVID0qoAwIcPisiutj8e6P1j5cxUOxNr1', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'CONFISER', 'Parametros de CONFISER', 'C:\Program Files\Microsoft Office\OFFICE11\winword.exe10.1.96.2 ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'CTRLGCIAS ', 'Parametros de CTRLGCIAS ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'CTRLSAC ', 'Parametros de CTRLSAC ', '1234567 S01/05/200931/05/2009NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'CTRLSIJP', 'Parametros de CTRLSIJP', '12345671C:\PAYROLL4\CTRLSIJP.XLSC:\PROGRAM FILES\S.I.AP\AFIP\SIJP12\3 ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ELIMLIQ ', 'Parametros de ELIMLIQ ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'EMPCUR', 'Parametros de EMPCUR', 'N01/11/200830/11/2009N', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'EXDIFPER', 'Parametros de EXDIFPER', 'N01/02/200829/02/2008N7 ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'EXMANVAC01', 'Parametros de EXMANVAC01', 'N31/12/201131/01/2011NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'EXMANVAC02', 'Parametros de EXMANVAC02', 'N31/12/201131/01/2011NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'FD_BCO083D', 'Parametros de FD_BCO083D', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'FICHASM ', 'Parametros de FICHASM ', 'NNOMBRE01/02/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'FINIQUITO ', 'Parametros de FINIQUITO ', '//70000000010 0 ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'FQBORRAR', 'Parametros de FQBORRAR', '//70000000000 0 0// ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'IMPULTSEL ', 'Parametros de IMPULTSEL ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'INDEC ', 'Parametros de INDEC ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'INFSOX01', 'Parametros de INFSOX01', 'N01/09/200930/09/2009NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'IRHINDAU', 'Parametros de IRHINDAU', 'N01/10/200931/10/2009NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'IRHIRM', 'Parametros de IRHIRM', 'N01/02/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'LIBROMICROF ', 'Parametros de LIBROMICROF ', '1234567 NTODOS 01/03/201331/03/2013C:\BASES\MICROFICHAS.TXTNM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'LIBROREM01', 'Parametros de LIBROREM01', '17NCODIGO01/02/201128/02/2011NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_BORRARED ', 'Parametros de ME_BORRARED ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_CALCUDTR ', 'Parametros de ME_CALCUDTR ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_CAMBIOSH ', 'Parametros de ME_CAMBIOSH ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_CICLOCAP ', 'Parametros de ME_CICLOCAP ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_CORRMONTO', 'Parametros de ME_CORRMONTOA ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_CORRSAC', 'Parametros de ME_CORRSAC', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_CTRLFOTOS', 'Parametros de ME_CTRLFOTOS', 'N01/02/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_CTRLM', 'Parametros de ME_CTRLM', '1234567 N01/02/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_DETA_AYB ', 'Parametros de ME_DETA_AYB ', 'N01/05/200829/05/2009NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_DETAAUS', 'Parametros de ME_DETAAUS', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_DETALIQ', 'Parametros de ME_DETALIQ', '1234567 STODOS 01/08/200331/08/2003NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_DETANUAL ', 'Parametros de ME_DETANUAL ', '1234567 N01/02/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_DETGANANU', 'Parametros de ME_DETGANANU', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_FICHAS ', 'Parametros de ME_FICHAS ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_GRILLCAP ', 'Parametros de ME_GRILLCAP ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_IRHHCM ', 'Parametros de ME_IRHHCM ', 'N01/02/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_LLENARUB ', 'Parametros de ME_LLENARUB ', 'N01/01/201131/01/2011NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_MEORGANI ', 'Parametros de ME_MEORGANI ', 'N01/02/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_REASIFAM ', 'Parametros de ME_REASIFAM ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_RESUITM', 'Parametros de ME_RESUITM', '7 N01/02/200829/02/2008C:\PayRoll4\Ejemplo.xls NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'ME_RESUPR ', 'Parametros de ME_RESUPR ', '1234567 N01/01/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'MOLESTO ', 'Parametros de MOLESTO ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RACTRES ', 'Parametros de RACTRES ', '31/01/200830/06/20080 ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RCERTIA ', 'Parametros de RCERTIA ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RCIESUE ', 'Parametros de RCIESUE ', '//717 FF0Centro de costo AREMILIA ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RCONDIS ', 'Parametros de RCONDIS ', 'BORRAR', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RCONTAB ', 'Parametros de RCONTAB ', '1071 2C:\PAYROLL4\SSS.csv ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RCONTRA ', 'Parametros de RCONTRA ', '01/08/2003SOLICITUD BK.RTFBORRAR 1', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RCTACOR ', 'Parametros de RCTACOR ', ' 0 0 0', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RCURRICU', 'Parametros de RCURRICU', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RDESBLO ', 'Parametros de RDESBLO ', '7 ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RECMEJREM ', 'Parametros de RECMEJREM ', 'N01/07/201331/07/2013NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'REDIEVE ', 'Parametros de REDIEVE ', '18/11/201301/01/3000 10000', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'REMPCUR ', 'Parametros de REMPCUR ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'REMPLES ', 'Parametros de REMPLES ', 'N ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RENVICLA', 'Parametros de RENVICLA', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RESUITM01 ', 'Parametros de RESUITM01 ', '1234567 N01/05/201330/05/2013C:\CARPETA TEMPORARIA\ADP.XLS NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RESUITM11 ', 'Parametros de RESUITM11 ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RESUITMCAS01', 'Parametros de RESUITMCAS01', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RESUPRDIF ', 'Parametros de RESUPRDIF ', '1234567 N01/01/200829/02/2008NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'REVISACAT ', 'Parametros de REVISACAT ', 'N01/02/200928/02/2009NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RGA3008B', 'Parametros de RGA3008B', 'N01/01/201131/01/2011NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RHONING1', 'Parametros de RHONING1', '0F', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RIMPPLE ', 'Parametros de RIMPPLE ', 'TT', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RINGDAT1', 'Parametros de RINGDAT1', ' 0 0 0 0 0//', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RINGDAT2', 'Parametros de RINGDAT2', '2 ExcelC:\BASES\BASEMODELO_V1\RATRIL INTER.XLS', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RINGPLA ', 'Parametros de RINGPLA ', '70 2 022', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RINGPLAI', 'Parametros de RINGPLAI', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RITMEMP ', 'Parametros de RITMEMP ', '71A000 100502010 5 2 10,500,250,10', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RLAUSENT', 'Parametros de RLAUSENT', 'FRANCO', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RLHORASEX ', 'Parametros de RLHORASEX ', 'F ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RLIBROR ', 'Parametros de RLIBROR ', '10007 Todos juntos 0', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RMANCIE ', 'Parametros de RMANCIE ', '7BORRAR1', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RMANPLE ', 'Configuracion: PERSONAL ', 'BORRAR, BORRAR;BORRAR ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RPLASUE ', 'Parametros de RPLASUE ', '72Codigo del empleado ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RPLIQUI ', 'Parametros de RPLIQUI ', '7;', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RPREFEMP', 'Parametros de RPREFEMP', '0000000 ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RRESCOS ', 'Parametros de RRESCOS ', '70F ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RRESLIQ ', 'Parametros de RRESLIQ ', '72Centro de costo ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RVACACI ', 'Parametros de RVACACI ', '031/12/20121', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RVACCOM ', 'Parametros de RVACCOM ', '01/08/200931/08/2009', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RVERMAR ', 'Parametros de RVERMAR ', '100007', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'RWIZAMA3', 'Parametros de RWIZAMA3', 'C:\ C:\USERS\MGARCIA\DESKTOP\MOD25839.DBF ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'SOPORTE14 ', 'Parametros de SOPORTE14 ', 'N01/07/201331/07/2013NM ', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PERSONAL', 'USUBCONJUNTO', 'Parametros de USUBCONJUNTO', 'NO', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('PRUEBAS ', 'REMPLES ', 'Parametros de REMPLES ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('USERPAY ', 'REMPLES ', 'Parametros de REMPLES ', '', 0);
INSERT INTO RPAUSER(Usuario, Copar, Descrip, Param, Jdd) VALUES ('USERPAY ', 'RPREFEMP', 'Parametros de RPREFEMP', '', 0);
