INSERT INTO Rubdgi(codigo, descrip) VALUES ('1a ', 'Liquidadas por la entidad que actua como agente de retención');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('1b ', 'Liquidadas por otras personas o entidades ');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('2a ', 'Aportes jubilatorios');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('2b ', 'Aportes para obras sociales y cuotas médico asistenciales ');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('2c ', 'Primas de seguro para caso de muerte');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('2d ', 'Gastos de sepelio ');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('2e ', 'Gastos estimados de corredores y viajantes');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('2f ', 'Otras deducciones ');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('4', 'Donaciones');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('6a ', 'Deducción Especial');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('9a ', 'Retenciones efectuadas en el período');
INSERT INTO Rubdgi(codigo, descrip) VALUES ('9b ', 'Regimenes de promoción');
