INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC12537', 'TBCASNMO', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', ' ', '', '', 1, '', '', 2, 'SELECT * FROM TBCASNMO', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA', ' ', 'PERSONAL', 9999, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC16853', 'tbrhuids', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', ' ', '', '', 1, '', '', 2, 'SELECT * from TBRHUIDS', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA', ' ', 'PERSONAL', 9999, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC26621', 'Reporte de Nov. (Acumulada) ', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', 'ESTADO =''A'' ', '', '1 ', 2, 'I.H00007,I.H00008,I.H00009,I.H00015,I.H00028,I.H00029,I.H00030,I.H00031,I.H00033,I.H00034,I.H00035,I.H00038,I.H00040,I.H00041,I.H00045,I.H00203,I.H00204,I.H00205,I.H00206', '', 3, 'SELECT q.CODIGO, q.NOMBRE FROM REMPLES q WHERE ESTADO =''A''', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA,LIQUIDA,SUPERV_CAS,CONSULTA', ' ', 'PERSONAL', 9999, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC35227', 'Reporte de Novedades', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', ' ESTADO =''A''', '', '1 ', 4, 'I.H00007,I.H00008,I.H00009,I.H00015,I.H00028,I.H00029,I.H00030,I.H00031,I.H00033,I.H00034,I.H00035,I.H00038,I.H00040,I.H00041,I.H00045,I.H00203,I.H00204,I.H00205,I.H00206', '', 3, 'SELECT q.CODIGO, q.NOMBRE FROM REMPLES q WHERE ESTADO =''A''', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA,LIQUIDA,RRHH,CONSULTA', ' ', 'MMUINOS ', 9999, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC41353', 'Reporte Ll.Tarde (Acumulada)', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', 'ESTADO =''A'' ', '', '1 ', 2, 'I.LTARDE', '', 3, 'SELECT q.CODIGO, q.NOMBRE FROM REMPLES q WHERE ESTADO =''A''', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA,LIQUIDA,SUPERV_CAS,CONSULTA', ' ', 'PERSONAL', 9999, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC44046', 'TBCASNOV', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', ' ', '', '', 1, '', '', 2, 'SELECT * from tbcasnov', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA', ' ', 'PERSONAL', 9999, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC82008', 'Reporte Ll.Tarde', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', ' ESTADO =''A''', '', '', 4, 'I.LTARDE', '', 3, 'SELECT q.CODIGO, q.NOMBRE FROM REMPLES q WHERE ESTADO =''A''', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA,LIQUIDA,ADMINISTRA,SUPERV_CAS,CONSULTA ', ' ', 'MMUINOS ', 9999, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC84661', '', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', ' ', '', '', 11, '', '', 3, 'SELECT q.CODIGO, q.NOMBRE FROM REMPLES q', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA', ' ', 'PERSONAL', 10, 0);
INSERT INTO tbcas_rhu(Modulo, Descrip, Tipo, Campos, Desde, Filtro, Agrupa, Orden, Tipper, Cohades, Usuario, Indir, Directa, Swhere, Pwhere, org, cabecera, visibles, nperiodo, Pexpre, grupos, varis, dueno, clasif, jdd) VALUES ('MDC85412', 'DESC. PRESENTISMO ', ' ', 'q.CODIGO, q.NOMBRE', 'REMPLES q', ' ', '', '', 3, 'I.DESPRE', '', 3, 'SELECT q.CODIGO, q.NOMBRE FROM REMPLES q', '', '', ' ', '', '', 0, ' ', 'ADMINISTRA', ' ', 'PERSONAL', 30, 0);
