INSERT INTO tbcascfg(clave, valor, valor2) VALUES (1, 'C:\FICHADAS\REGIS.CRO ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2, '2 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (20, ' 1', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (21, '4,00', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (22, '15', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (23, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (24, '23:59 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (25, ' 1', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (28, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (29, ' 1', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (31, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (35, ' 1', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (36, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (37, ' 1', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (38, ' 1', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (39, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (40, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (41, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (42, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (50, '3 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (51, 'C:\FICHADAS\leidos\REGIS??????????.CRO', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (52, '1 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (53, '1 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (59, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (60, '21/03/2012 10:04:34 AM', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (61, ' 400', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (62, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (63, '1 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (79, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (91, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (92, 'Nada', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (93, 'C:\PAYROLL\RELOJ\BAK\IMPFICHAD???.xls ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (95, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (96, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (97, '1 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (400, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (401, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (419, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (420, ': ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (421, ': ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (422, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (423, ': ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (424, ': ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (425, ': ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (426, ' 0', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (427, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (430, 'F ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (431, '2 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (432, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (433, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (434, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (435, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (440, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (500, '0 ', '0 ');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (501, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (510, '24', '2 ');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (511, '01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (512, '0 ', '0 ');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (513, '1 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (520, '1 ', '5 ');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (530, '7 ', 'dd/mm/aaaa');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (540, '18', 'hh:mm ');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (550, '27', '2 ');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (551, '20', '21');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (601, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (602, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (603, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (604, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (605, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (606, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (607, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (608, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (609, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (610, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (611, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (612, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (613, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (614, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (615, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (616, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (617, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (618, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (619, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (620, '0 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (1000, '6 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (1001, '6 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (1004, '6 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2000, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2001, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2010, 'C8HTAR', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2011, 'C8HAUS', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2012, 'C1HTRA', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2013, 'H00008', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2014, 'H00009', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2015, 'T ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2016, 'NOAUTO', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2017, ' 1', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2020, 'H00021', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2021, 'H00020', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2022, 'H00045', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2023, 'H00041', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2024, 'H00040', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2025, 'H00203', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2026, 'C2HASA', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2027, 'H00204', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2028, 'H00034', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2029, 'H00007', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2030, 'H00205', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2031, 'H00028', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2032, 'H00031', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2033, 'H00030', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2034, 'H00035', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2035, 'H00033', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2036, 'H00029', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2037, 'H00206', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2038, 'H00015', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2039, 'H00038', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2040, 'LTARDE', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2041, '101,102,111 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2042, '101,102,111 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2043, '101,102,111 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2044, '101,102,111 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2045, '1410', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2046, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2047, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2048, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2049, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2050, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2051, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2052, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2053, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2054, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2055, '101,102,111 ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2056, '', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2070, 'F ', '');
INSERT INTO tbcascfg(clave, valor, valor2) VALUES (2100, ' 1', '');
